#!/bin/sh
hash=`git rev-parse HEAD | cut -b -8`
#echo "Hash: $hash"

echo "/*"
echo -n "Automatically generated by genhash.sh on "
echo `date`
echo
echo "Any changes made to this file will be lost."
echo "*/"
echo
echo "#define BUILD_HASH \"$hash\""
