FIND_PATH(XXF86VM_INCLUDE_DIR NAMES X11/extensions/xf86vmode.h)
FIND_LIBRARY(XXF86VM_LIBRARY NAMES Xxf86vm)

IF (XXF86VM_INCLUDE_DIR AND XXF86VM_LIBRARY)
   SET(XXF86VM_FOUND TRUE)
ENDIF (XXF86VM_INCLUDE_DIR AND XXF86VM_LIBRARY)

IF (XXF86VM_FOUND)
   IF (NOT XXF86VM_FIND_QUIETLY)
      MESSAGE(STATUS "Found xxf86vm: ${XXF86VM_LIBRARY}")
   ENDIF (NOT XXF86VM_FIND_QUIETLY)
ELSE (XXF86VM_FOUND)
   IF (XXF86VM_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find xxf86vm-dev")
   ENDIF (XXF86VM_FIND_REQUIRED)
ENDIF (XXF86VM_FOUND)

